interface Props {
  onNavigate: (path: string) => void;
}

// Terms & Disclaimer. Bracketed [PLACEHOLDERS] must be filled before launch,
// and the whole document should be reviewed by a licensed attorney — it is a
// starting template, not legal advice.
const SECTIONS: Array<{ n: string; title: string; body: string[] }> = [
  {
    n: '01',
    title: 'What Quote Check is — and is not',
    body: [
      'Quote Check provides algorithmically generated, informational price estimates and educational content about residential HVAC and heat-pump systems. The fair-price ranges are produced by a deterministic model from public and aggregated market data.',
      'These estimates are approximations and starting points for your own research. They are NOT professional, financial, investment, engineering, tax, or legal advice, and they are NOT a substitute for a licensed HVAC contractor’s on-site assessment or a written quote.',
    ],
  },
  {
    n: '02',
    title: 'No advice, no advisory relationship',
    body: [
      'Nothing on this site constitutes financial, purchasing, or professional advice, and nothing creates an advisory, fiduciary, agency, brokerage, or professional relationship between you and us. You alone are responsible for your purchasing decisions.',
    ],
  },
  {
    n: '03',
    title: 'Estimates are not guarantees',
    body: [
      'Actual installed prices depend on factors we cannot observe — your home, ductwork, electrical, permitting, equipment availability, labor markets, and individual contractor pricing — and will differ, sometimes significantly, from our ranges.',
      'We do not guarantee that any estimate reflects a price you can actually obtain, or that a quote we label “Low,” “Fair,” or “High” is in fact low, fair, or high for your specific situation.',
    ],
  },
  {
    n: '04',
    title: 'AI-generated explanations',
    body: [
      'Written summaries and explanations are generated by AI and may be inaccurate, incomplete, or out of date. The numeric ranges are deterministic but remain estimates. Independently verify anything you intend to rely on.',
    ],
  },
  {
    n: '05',
    title: 'Do your own diligence',
    body: [
      'Always obtain multiple written quotes and consult licensed, insured professionals before purchasing, financing, or signing anything. Use our estimates to inform the questions you ask — not to replace professional judgment.',
    ],
  },
  {
    n: '06',
    title: 'Third parties',
    body: [
      'We are not affiliated with, and do not endorse, recommend, or vouch for, any contractor, installer, manufacturer, or lender. We are not a party to, and are not responsible for, any transaction, quote, contract, or dispute between you and any third party.',
    ],
  },
  {
    n: '07',
    title: 'Provided “as is,” no warranties',
    body: [
      'The site and all content are provided “as is” and “as available,” without warranties of any kind, express or implied — including accuracy, completeness, merchantability, fitness for a particular purpose, and non-infringement — to the fullest extent permitted by law.',
    ],
  },
  {
    n: '08',
    title: 'Limitation of liability',
    body: [
      'To the maximum extent permitted by law, Alumni Founders, Inc. and its owners, operators, and contributors will not be liable for any indirect, incidental, consequential, special, exemplary, or punitive damages, or for any loss of money, profits, or expected savings, arising out of or relating to your use of or reliance on the site or any estimate or content — including any decision to purchase or not purchase, any amount you paid a contractor, or any dispute with a third party — even if we were advised of the possibility.',
      'Our total aggregate liability for any claim will not exceed the greater of (a) the amount you paid us for the specific service giving rise to the claim in the twelve months before the claim, or (b) US $50.',
    ],
  },
  {
    n: '09',
    title: 'Indemnification',
    body: [
      'You agree to indemnify and hold harmless Alumni Founders, Inc. from any claims, losses, or expenses arising out of your misuse of the site or your violation of these terms.',
    ],
  },
  {
    n: '10',
    title: 'No regulated services',
    body: [
      'We do not provide brokerage, lending, insurance, or investment services, and nothing on this site is an offer or solicitation for any such service.',
    ],
  },
  {
    n: '11',
    title: 'Purchases and refunds',
    body: [
      'Most of Quote Check is free. The optional detailed report is a one-time US $9 charge, processed by Stripe — there is no subscription and nothing auto-renews.',
      'Because the report is delivered instantly as digital content, all sales are final and payments are non-refundable, except where a refund is required by law. If the report failed to generate, was not delivered, or you were charged in error, email us within 30 days and we will make it right.',
    ],
  },
  {
    n: '12',
    title: 'Changes',
    body: [
      'We may update these terms and the pricing methodology at any time. Material changes take effect when posted, and your continued use of the site means you accept them.',
    ],
  },
  {
    n: '13',
    title: 'Governing law',
    body: [
      'These terms are governed by the laws of the State of California, without regard to its conflict-of-laws rules. Any dispute will be brought exclusively in the state or federal courts located in California.',
    ],
  },
];

export default function LegalPage({ onNavigate }: Props) {
  return (
    <div className="mx-auto w-full max-w-3xl px-5 pb-24 sm:px-8">
      <div className="sheet mt-10">
        <div className="sheet-titleblock">
          <span>Sheet Nº 004 — terms &amp; disclaimer</span>
          <span className="ml-auto">effective July 21, 2026</span>
        </div>

        <div className="px-5 py-8 sm:px-8 sm:py-10">
          <h1 className="font-display text-4xl leading-tight tracking-tight text-ink sm:text-5xl">
            Terms &amp; Disclaimer
          </h1>
          <p className="mt-4 max-w-[68ch] text-[13px] leading-relaxed text-ink-soft">
            Quote Check is operated by Alumni Founders, Inc. (“we,” “us”). By using this site you agree to the
            terms below. Read them — they describe what our estimates are, what they are not,
            and the limits of our responsibility.
          </p>

          <div className="mt-8 space-y-7">
            {SECTIONS.map((s) => (
              <section key={s.n} className="border-t border-ink/15 pt-5">
                <h2 className="flex gap-3 font-mono text-[12px] uppercase tracking-micro text-ink-mute">
                  <span className="text-copper-deep">{s.n}</span>
                  <span>{s.title}</span>
                </h2>
                <div className="mt-3 space-y-3">
                  {s.body.map((p, i) => (
                    <p key={i} className="max-w-[68ch] text-[13px] leading-relaxed text-ink-soft">
                      {p}
                    </p>
                  ))}
                </div>
              </section>
            ))}

            <section className="border-t border-ink/15 pt-5">
              <h2 className="flex gap-3 font-mono text-[12px] uppercase tracking-micro text-ink-mute">
                <span className="text-copper-deep">14</span>
                <span>Contact</span>
              </h2>
              <p className="mt-3 text-[13px] leading-relaxed text-ink-soft">
                Questions about these terms: hello@alumnifounders.com.
              </p>
            </section>
          </div>

          <div className="mt-10 flex flex-wrap gap-3">
            <button onClick={() => onNavigate('/')} className="btn-line">
              ← Back to the fair price
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
